package com.aiworkspace.audit.domain.model;

public enum AuditEventType {
    // IAM
    USER_REGISTERED,
    // Documents
    DOCUMENT_UPLOADED,
    DOCUMENT_INDEXED,
    DOCUMENT_DELETED,
    DOCUMENT_QUERIED,
    // Learning
    COURSE_CREATED,
    COURSE_PUBLISHED,
    ENROLLED,
    LESSON_COMPLETED,
    COURSE_COMPLETED,
    CERTIFICATE_ISSUED,
    // Billing
    TRIAL_STARTED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELED,
    SUBSCRIPTION_EXPIRED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    QUOTA_EXCEEDED,
    // Notifications
    NOTIFICATION_SENT,
    NOTIFICATION_FAILED
}
