package com.aiworkspace.billing.infrastructure.scheduler;

import com.aiworkspace.billing.application.port.out.BillingNotificationPort;
import com.aiworkspace.billing.application.port.out.SubscriptionRepository;
import com.aiworkspace.billing.application.service.InvoiceService;
import com.aiworkspace.billing.domain.model.Subscription;
import com.aiworkspace.billing.domain.model.SubscriptionStatus;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;

@Component
public class BillingRenewalScheduler {

    private static final Logger log = LoggerFactory.getLogger(BillingRenewalScheduler.class);
    private static final int TRIAL_EXPIRY_WARNING_DAYS = 3;

    private final SubscriptionRepository subscriptionRepository;
    private final InvoiceService invoiceService;
    private final BillingNotificationPort notificationPort;
    private final ApplicationEventPublisher eventPublisher;
    private final Counter expiredCounter;
    private final Counter renewedCounter;

    public BillingRenewalScheduler(SubscriptionRepository subscriptionRepository,
                                    InvoiceService invoiceService,
                                    BillingNotificationPort notificationPort,
                                    ApplicationEventPublisher eventPublisher,
                                    MeterRegistry meterRegistry) {
        this.subscriptionRepository = subscriptionRepository;
        this.invoiceService = invoiceService;
        this.notificationPort = notificationPort;
        this.eventPublisher = eventPublisher;
        this.expiredCounter = Counter.builder("billing.subscriptions.expired")
                .description("Total subscriptions expired by scheduler").register(meterRegistry);
        this.renewedCounter = Counter.builder("billing.invoices.generated")
                .description("Total invoices generated by renewal scheduler").register(meterRegistry);
    }

    @Scheduled(cron = "${billing.renewal.cron:0 0 2 * * *}")
    @Transactional
    public void processExpiredTrials() {
        Instant now = Instant.now();
        List<Subscription> expiredTrials = subscriptionRepository.findExpiring(
                SubscriptionStatus.TRIAL, now);

        for (Subscription trial : expiredTrials) {
            try {
                trial.expire();
                subscriptionRepository.save(trial);
                trial.getDomainEvents().forEach(eventPublisher::publishEvent);
                trial.clearDomainEvents();
                expiredCounter.increment();
                log.info("Trial expired subscriptionId={} userId={}", trial.getId(), trial.getUserId());
            } catch (Exception e) {
                log.error("Failed to expire trial subscriptionId={}", trial.getId(), e);
            }
        }
    }

    @Scheduled(cron = "${billing.renewal.cron:0 0 2 * * *}")
    @Transactional
    public void generateRenewalInvoices() {
        Instant tomorrow = Instant.now().plus(1, ChronoUnit.DAYS);
        List<Subscription> renewingSubscriptions = subscriptionRepository.findExpiring(
                SubscriptionStatus.ACTIVE, tomorrow);

        for (Subscription subscription : renewingSubscriptions) {
            try {
                invoiceService.generateForSubscription(subscription.getId(), subscription.getUserId());
                renewedCounter.increment();
                log.info("Renewal invoice generated subscriptionId={}", subscription.getId());
            } catch (Exception e) {
                log.error("Failed to generate renewal invoice subscriptionId={}", subscription.getId(), e);
            }
        }
    }

    @Scheduled(cron = "${billing.trial-warning.cron:0 0 10 * * *}")
    @Transactional(readOnly = true)
    public void notifyTrialExpiringSoon() {
        Instant warningThreshold = Instant.now().plus(TRIAL_EXPIRY_WARNING_DAYS, ChronoUnit.DAYS);
        List<Subscription> expiringTrials = subscriptionRepository.findExpiring(
                SubscriptionStatus.TRIAL, warningThreshold);

        for (Subscription trial : expiringTrials) {
            try {
                notificationPort.notifyTrialExpiringSoon(trial.getUserId(), TRIAL_EXPIRY_WARNING_DAYS);
            } catch (Exception e) {
                log.error("Failed to send trial warning userId={}", trial.getUserId(), e);
            }
        }
    }
}
